"""add_asset_fields

Revision ID: e145d65f88fa
Revises: 69b0e837dc93
Create Date: 2026-07-12 17:05:49.656749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e145d65f88fa'
down_revision: Union[str, None] = '69b0e837dc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('acquisition_date', sa.DateTime(), nullable=True))
    op.add_column('assets', sa.Column('acquisition_cost', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('condition', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('is_shared_bookable', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'is_shared_bookable')
    op.drop_column('assets', 'photo_url')
    op.drop_column('assets', 'condition')
    op.drop_column('assets', 'acquisition_cost')
    op.drop_column('assets', 'acquisition_date')
    # ### end Alembic commands ###
